---
- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/init/main.yml

- hosts: oo_first_master
  roles:
  - role: /usr/share/ansible/openshift-ansible/roles/openshift_manage_node
    openshift_master_host: "{{ groups.oo_first_master.0 }}"
    openshift_manage_node_is_master: "{{ ('oo_masters_to_config' in group_names) | bool }}"
